[project]
name = "pixelflow"
version = "0.1.1"
description = "Reusable computer vision tools"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Datamarkin", email = "support@datamarkin.com"},
    {name = "Emrah Nazif", email = "emrah@datamarkin.com"}
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "shapely>=2.0.0",  # Add dependencies here
    "numpy>=1.21.0",
    "opencv-python>=4.8.0",
    "scipy>=1.10.0"
]

[tool.setuptools.packages.find]
include = ["pixelflow*"]
exclude = ["tests*", "docs*", "examples*", "scripts*"]
