[project]
name = "pixelflow"
version = "0.1.0"
description = "Reusable computer vision tools"
requires-python = ">=3"
license = {text = "MIT License"}
authors = [
    {name = "Datamarkin", email = "support@datamarkin.com"}
]

classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

dependencies = [
    "shapely>=2.0.0",  # Add dependencies here
    "numpy>=1.21.0",
    "opencv-python>=4.8.0",
    "scipy>=1.10.0"
]