"""COCO label constants for use with detection converters."""

from typing import Any, Dict, List

COCO_LABELS: List[Dict[str, Any]] = [
    {
        "id": 0,
        "name": "person",
        "keypoints": [
            {"id": 0, "name": "nose"},
            {"id": 1, "name": "left_eye"},
            {"id": 2, "name": "right_eye"},
            {"id": 3, "name": "left_ear"},
            {"id": 4, "name": "right_ear"},
            {"id": 5, "name": "left_shoulder"},
            {"id": 6, "name": "right_shoulder"},
            {"id": 7, "name": "left_elbow"},
            {"id": 8, "name": "right_elbow"},
            {"id": 9, "name": "left_wrist"},
            {"id": 10, "name": "right_wrist"},
            {"id": 11, "name": "left_hip"},
            {"id": 12, "name": "right_hip"},
            {"id": 13, "name": "left_knee"},
            {"id": 14, "name": "right_knee"},
            {"id": 15, "name": "left_ankle"},
            {"id": 16, "name": "right_ankle"},
        ],
        "skeleton": [
            [0, 1], [0, 2], [1, 3], [2, 4],
            [5, 6], [5, 7], [7, 9], [6, 8], [8, 10],
            [5, 11], [6, 12], [11, 12],
            [11, 13], [13, 15], [12, 14], [14, 16],
        ],
    },
    {"id": 1, "name": "bicycle"},
    {"id": 2, "name": "car"},
    {"id": 3, "name": "motorcycle"},
    {"id": 4, "name": "airplane"},
    {"id": 5, "name": "bus"},
    {"id": 6, "name": "train"},
    {"id": 7, "name": "truck"},
    {"id": 8, "name": "boat"},
    {"id": 9, "name": "traffic light"},
    {"id": 10, "name": "fire hydrant"},
    {"id": 11, "name": "stop sign"},
    {"id": 12, "name": "parking meter"},
    {"id": 13, "name": "bench"},
    {"id": 14, "name": "bird"},
    {"id": 15, "name": "cat"},
    {"id": 16, "name": "dog"},
    {"id": 17, "name": "horse"},
    {"id": 18, "name": "sheep"},
    {"id": 19, "name": "cow"},
    {"id": 20, "name": "elephant"},
    {"id": 21, "name": "bear"},
    {"id": 22, "name": "zebra"},
    {"id": 23, "name": "giraffe"},
    {"id": 24, "name": "backpack"},
    {"id": 25, "name": "umbrella"},
    {"id": 26, "name": "handbag"},
    {"id": 27, "name": "tie"},
    {"id": 28, "name": "suitcase"},
    {"id": 29, "name": "frisbee"},
    {"id": 30, "name": "skis"},
    {"id": 31, "name": "snowboard"},
    {"id": 32, "name": "sports ball"},
    {"id": 33, "name": "kite"},
    {"id": 34, "name": "baseball bat"},
    {"id": 35, "name": "baseball glove"},
    {"id": 36, "name": "skateboard"},
    {"id": 37, "name": "surfboard"},
    {"id": 38, "name": "tennis racket"},
    {"id": 39, "name": "bottle"},
    {"id": 40, "name": "wine glass"},
    {"id": 41, "name": "cup"},
    {"id": 42, "name": "fork"},
    {"id": 43, "name": "knife"},
    {"id": 44, "name": "spoon"},
    {"id": 45, "name": "bowl"},
    {"id": 46, "name": "banana"},
    {"id": 47, "name": "apple"},
    {"id": 48, "name": "sandwich"},
    {"id": 49, "name": "orange"},
    {"id": 50, "name": "broccoli"},
    {"id": 51, "name": "carrot"},
    {"id": 52, "name": "hot dog"},
    {"id": 53, "name": "pizza"},
    {"id": 54, "name": "donut"},
    {"id": 55, "name": "cake"},
    {"id": 56, "name": "chair"},
    {"id": 57, "name": "couch"},
    {"id": 58, "name": "potted plant"},
    {"id": 59, "name": "bed"},
    {"id": 60, "name": "dining table"},
    {"id": 61, "name": "toilet"},
    {"id": 62, "name": "tv"},
    {"id": 63, "name": "laptop"},
    {"id": 64, "name": "mouse"},
    {"id": 65, "name": "remote"},
    {"id": 66, "name": "keyboard"},
    {"id": 67, "name": "cell phone"},
    {"id": 68, "name": "microwave"},
    {"id": 69, "name": "oven"},
    {"id": 70, "name": "toaster"},
    {"id": 71, "name": "sink"},
    {"id": 72, "name": "refrigerator"},
    {"id": 73, "name": "book"},
    {"id": 74, "name": "clock"},
    {"id": 75, "name": "vase"},
    {"id": 76, "name": "scissors"},
    {"id": 77, "name": "teddy bear"},
    {"id": 78, "name": "hair drier"},
    {"id": 79, "name": "toothbrush"},
]
